server:
  port: 3001
spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/github-yangwanhao/spring-cloud.git
          username: 'yangwanhao163@163.com'
          password: xujuan199689
          search-paths: spring-cloud-config/*
          default-label: dev
          basedir: /data/config/config-repo
          # 强制更新
          force-pull: true