server:
  port: 6001
spring:
  application:
    name: controller-service2
eureka:
  username: yangwanhao
  password: eureka
  client:
    service-url:
      defaultZone: http://${eureka.username}:${eureka.password}@localhost:1001/eureka/,http://${eureka.username}:${eureka.password}@localhost:2001/eureka/
    # eureka client间隔多久去拉取服务注册信息
    registry-fetch-interval-seconds: 5