server:
  port: 2001
spring:
  application:
    name: eureka-two
  security:
    user:
      name: yangwanhao
      password: eureka
eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://yangwanhao:eureka@localhost:1001/eureka/
    # 禁止自己注册自己
    # register-with-eureka: false
    # fetch-registry: false
  server:
    # 关闭自我保护
    enable-self-preservation: false
    # 每隔5秒进行一次服务列表清理
    eviction-interval-timer-in-ms: 5000