server:
  port: 5001
spring:
  application:
    name: controller-service1
eureka:
  client:
    service-url:
      defaultZone: http://yangwanhao:eureka@eureka1:1001/eureka/,http://yangwanhao:eureka@eureka2:2001/eureka/
    # eureka client间隔多久去拉取服务注册信息
    registry-fetch-interval-seconds: 5